[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tugrul Agrikli", email = "tugrul.agrikli@parkolay.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pymupdf>=1.28.2",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
